### ISSUE TITLE
需要 ideas

### ISSUE THREAD

**Issue by zhaolion** [kit-x/pine#2]
@liluo @rush24 @aristotll @jackie716 提出你的 idea，让东半球开始转动

**Comment by zhaolion** [comment]
- 支持 sql file migration
- 支持 clusters
- 读写分离

**Comment by liluo** [comment]
> 支持 clusters

是指什么？

**Comment by zhaolion** [comment]
> > 支持 clusters
> 
> 是指什么？

一个 Group: 1 master + N slave, cluster 就是 N 个 group

**Comment by rush24** [comment]
> 一个 Group: 1 master + N slave, cluster 就是 N 个 group

这算 sharding 么

**Comment by zhaolion** [comment]
> > 一个 Group: 1 master + N slave, cluster 就是 N 个 group
> 
> 这算 sharding 么

不是，就是一组数据库 master/salves 可以同步接入，自动读写分离。sharding 是一个单独的功能

**Comment by zhaolion** [comment]
add your features to https://github.com/kit-x/pine/projects/2
